name: first_flutter_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  http: ^1.4.0
  shared_preferences: ^2.0.17
  intl: ^0.20.2
  cloud_firestore: ^5.6.9
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.2
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  # 移除了重複的 http 依賴
  flutter_lints: ^5.0.0
  flutter_rating_bar: ^4.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/